import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full  justify-center items-center overflow-auto ">
      {children}
    </div>
  );
}
