import AuthImage from "@/components/AuthImage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <div className="flex h-screen w-full flex-col items-center overflow-auto lg:flex-row">
        <AuthImage />
        {children}
      </div>
    );
}
