import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "../context/AppContext";
import { ConvexClientProvider } from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <AppProvider>
        <html lang="en">
          <body>
            <div className="h-screen w-full bg-background text-white">
              {children}
            </div>
          </body>
        </html>
      </AppProvider>
    </ConvexClientProvider>
  );
}
