import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "../context/AppContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AppProvider>
        <html lang="en">
          <body>
            <div className="h-screen w-full bg-background text-white">
              {children}
              <Toaster />
            </div>
          </body>
        </html>
      </AppProvider>
    </>
  );
}
