import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-full bg-background text-white">{children}</div>
      </body>
    </html>
  );
}
