import LeftNavbar from "@/components/LeftNavbar";
import type { Metadata } from "next";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by simple",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <div className="flex h-screen w-full overflow-hidden">
        <LeftNavbar />
        {children}
      </div>
    </AppProvider>
  );
}
